export interface ProductSuggestie {
  naam: string
  categorie: string
}

// ~500 veelgekochte Nederlandse supermarktproducten
export const PRODUCTEN: ProductSuggestie[] = [
  // Zuivel & eieren
  { naam: "melk", categorie: "zuivel" },
  { naam: "halfvolle melk", categorie: "zuivel" },
  { naam: "volle melk", categorie: "zuivel" },
  { naam: "magere melk", categorie: "zuivel" },
  { naam: "havermelk", categorie: "zuivel" },
  { naam: "amandelmelk", categorie: "zuivel" },
  { naam: "sojamelk", categorie: "zuivel" },
  { naam: "rijstmelk", categorie: "zuivel" },
  { naam: "kokosmelk", categorie: "zuivel" },
  { naam: "karnemelk", categorie: "zuivel" },
  { naam: "boter", categorie: "zuivel" },
  { naam: "roomboter", categorie: "zuivel" },
  { naam: "margarine", categorie: "zuivel" },
  { naam: "halvarine", categorie: "zuivel" },
  { naam: "slagroom", categorie: "zuivel" },
  { naam: "kookroom", categorie: "zuivel" },
  { naam: "crème fraîche", categorie: "zuivel" },
  { naam: "yoghurt", categorie: "zuivel" },
  { naam: "griekse yoghurt", categorie: "zuivel" },
  { naam: "skyr", categorie: "zuivel" },
  { naam: "kwark", categorie: "zuivel" },
  { naam: "vla", categorie: "zuivel" },
  { naam: "chocoladevla", categorie: "zuivel" },
  { naam: "vanillevla", categorie: "zuivel" },
  { naam: "pudding", categorie: "zuivel" },
  { naam: "eieren", categorie: "zuivel" },
  { naam: "vrije uitloop eieren", categorie: "zuivel" },
  { naam: "biologische eieren", categorie: "zuivel" },

  // Kaas & vleeswaren
  { naam: "kaas", categorie: "kaas" },
  { naam: "gouda", categorie: "kaas" },
  { naam: "jonge kaas", categorie: "kaas" },
  { naam: "belegen kaas", categorie: "kaas" },
  { naam: "oude kaas", categorie: "kaas" },
  { naam: "extra belegen kaas", categorie: "kaas" },
  { naam: "smeerkaas", categorie: "kaas" },
  { naam: "mozzarella", categorie: "kaas" },
  { naam: "feta", categorie: "kaas" },
  { naam: "brie", categorie: "kaas" },
  { naam: "camembert", categorie: "kaas" },
  { naam: "parmezaan", categorie: "kaas" },
  { naam: "cheddar", categorie: "kaas" },
  { naam: "geitenkaas", categorie: "kaas" },
  { naam: "plakkaas", categorie: "kaas" },
  { naam: "geraspte kaas", categorie: "kaas" },
  { naam: "ham", categorie: "vleeswaren" },
  { naam: "gekookte ham", categorie: "vleeswaren" },
  { naam: "gerookte ham", categorie: "vleeswaren" },
  { naam: "salami", categorie: "vleeswaren" },
  { naam: "chorizo", categorie: "vleeswaren" },
  { naam: "kipfilet", categorie: "vleeswaren" },
  { naam: "kippenworst", categorie: "vleeswaren" },
  { naam: "leverworst", categorie: "vleeswaren" },
  { naam: "rookworst", categorie: "vleeswaren" },
  { naam: "bacon", categorie: "vleeswaren" },
  { naam: "ontbijtspek", categorie: "vleeswaren" },
  { naam: "paté", categorie: "vleeswaren" },

  // Brood & bakkerij
  { naam: "brood", categorie: "brood" },
  { naam: "witbrood", categorie: "brood" },
  { naam: "bruinbrood", categorie: "brood" },
  { naam: "volkorenbrood", categorie: "brood" },
  { naam: "meergranenbrood", categorie: "brood" },
  { naam: "roggebrood", categorie: "brood" },
  { naam: "zuurdesembrood", categorie: "brood" },
  { naam: "pistolets", categorie: "brood" },
  { naam: "ciabatta", categorie: "brood" },
  { naam: "baguette", categorie: "brood" },
  { naam: "stokbrood", categorie: "brood" },
  { naam: "croissants", categorie: "brood" },
  { naam: "boterkoek", categorie: "brood" },
  { naam: "crackers", categorie: "brood" },
  { naam: "beschuit", categorie: "brood" },
  { naam: "rijstwafels", categorie: "brood" },
  { naam: "knäckebröd", categorie: "brood" },
  { naam: "wraps", categorie: "brood" },
  { naam: "tortilla's", categorie: "brood" },
  { naam: "pita", categorie: "brood" },
  { naam: "bruine bolletjes", categorie: "brood" },
  { naam: "witte bolletjes", categorie: "brood" },

  // Vlees & vis
  { naam: "gehakt", categorie: "vlees" },
  { naam: "half-om-half gehakt", categorie: "vlees" },
  { naam: "rundergehakt", categorie: "vlees" },
  { naam: "kipgehakt", categorie: "vlees" },
  { naam: "kip", categorie: "vlees" },
  { naam: "kipfilet", categorie: "vlees" },
  { naam: "kippenborst", categorie: "vlees" },
  { naam: "kippendijen", categorie: "vlees" },
  { naam: "kipdijfilet", categorie: "vlees" },
  { naam: "gehele kip", categorie: "vlees" },
  { naam: "varkensvlees", categorie: "vlees" },
  { naam: "varkenshaas", categorie: "vlees" },
  { naam: "karbonade", categorie: "vlees" },
  { naam: "speklapjes", categorie: "vlees" },
  { naam: "biefstuk", categorie: "vlees" },
  { naam: "rundvlees", categorie: "vlees" },
  { naam: "lamskoteletten", categorie: "vlees" },
  { naam: "hamburgers", categorie: "vlees" },
  { naam: "worstjes", categorie: "vlees" },
  { naam: "worst", categorie: "vlees" },
  { naam: "zalm", categorie: "vis" },
  { naam: "zalmfilet", categorie: "vis" },
  { naam: "gerookte zalm", categorie: "vis" },
  { naam: "kabeljauw", categorie: "vis" },
  { naam: "tilapia", categorie: "vis" },
  { naam: "pangasius", categorie: "vis" },
  { naam: "tonijn", categorie: "vis" },
  { naam: "tonijn in blik", categorie: "vis" },
  { naam: "haring", categorie: "vis" },
  { naam: "makreel", categorie: "vis" },
  { naam: "garnalen", categorie: "vis" },
  { naam: "mosselen", categorie: "vis" },
  { naam: "vissticks", categorie: "vis" },

  // Groenten
  { naam: "tomaten", categorie: "groenten" },
  { naam: "cherrytomaten", categorie: "groenten" },
  { naam: "komkommer", categorie: "groenten" },
  { naam: "paprika", categorie: "groenten" },
  { naam: "rode paprika", categorie: "groenten" },
  { naam: "gele paprika", categorie: "groenten" },
  { naam: "groene paprika", categorie: "groenten" },
  { naam: "ui", categorie: "groenten" },
  { naam: "rode ui", categorie: "groenten" },
  { naam: "knoflook", categorie: "groenten" },
  { naam: "prei", categorie: "groenten" },
  { naam: "wortel", categorie: "groenten" },
  { naam: "wortelen", categorie: "groenten" },
  { naam: "broccoli", categorie: "groenten" },
  { naam: "bloemkool", categorie: "groenten" },
  { naam: "courgette", categorie: "groenten" },
  { naam: "aubergine", categorie: "groenten" },
  { naam: "spinazie", categorie: "groenten" },
  { naam: "sla", categorie: "groenten" },
  { naam: "ijsbergsla", categorie: "groenten" },
  { naam: "rucola", categorie: "groenten" },
  { naam: "veldsla", categorie: "groenten" },
  { naam: "kropsla", categorie: "groenten" },
  { naam: "andijvie", categorie: "groenten" },
  { naam: "witlof", categorie: "groenten" },
  { naam: "boontjes", categorie: "groenten" },
  { naam: "sperziebonen", categorie: "groenten" },
  { naam: "doperwten", categorie: "groenten" },
  { naam: "maïs", categorie: "groenten" },
  { naam: "champignons", categorie: "groenten" },
  { naam: "paddenstoelen", categorie: "groenten" },
  { naam: "avocado", categorie: "groenten" },
  { naam: "asperges", categorie: "groenten" },
  { naam: "paksoi", categorie: "groenten" },
  { naam: "spruitjes", categorie: "groenten" },
  { naam: "rode kool", categorie: "groenten" },
  { naam: "witte kool", categorie: "groenten" },
  { naam: "savooiekool", categorie: "groenten" },
  { naam: "venkel", categorie: "groenten" },
  { naam: "selderij", categorie: "groenten" },
  { naam: "peterselie", categorie: "groenten" },
  { naam: "basilicum", categorie: "groenten" },
  { naam: "bieslook", categorie: "groenten" },
  { naam: "dille", categorie: "groenten" },
  { naam: "munt", categorie: "groenten" },
  { naam: "gember", categorie: "groenten" },
  { naam: "jalapeño", categorie: "groenten" },
  { naam: "chili", categorie: "groenten" },
  { naam: "lente-ui", categorie: "groenten" },
  { naam: "radijs", categorie: "groenten" },
  { naam: "bieten", categorie: "groenten" },
  { naam: "zoete aardappelen", categorie: "groenten" },

  // Fruit
  { naam: "appels", categorie: "fruit" },
  { naam: "peren", categorie: "fruit" },
  { naam: "bananen", categorie: "fruit" },
  { naam: "sinaasappels", categorie: "fruit" },
  { naam: "mandarijnen", categorie: "fruit" },
  { naam: "citroenen", categorie: "fruit" },
  { naam: "limoenen", categorie: "fruit" },
  { naam: "druiven", categorie: "fruit" },
  { naam: "aardbeien", categorie: "fruit" },
  { naam: "frambozen", categorie: "fruit" },
  { naam: "blauwe bessen", categorie: "fruit" },
  { naam: "bramen", categorie: "fruit" },
  { naam: "kiwi", categorie: "fruit" },
  { naam: "mango", categorie: "fruit" },
  { naam: "ananas", categorie: "fruit" },
  { naam: "watermeloen", categorie: "fruit" },
  { naam: "meloen", categorie: "fruit" },
  { naam: "perziken", categorie: "fruit" },
  { naam: "nectarines", categorie: "fruit" },
  { naam: "pruimen", categorie: "fruit" },
  { naam: "kersen", categorie: "fruit" },
  { naam: "grapefruit", categorie: "fruit" },
  { naam: "papaja", categorie: "fruit" },
  { naam: "passievrucht", categorie: "fruit" },
  { naam: "vijgen", categorie: "fruit" },

  // Aardappelen, rijst & pasta
  { naam: "aardappelen", categorie: "koolhydraten" },
  { naam: "kruimige aardappelen", categorie: "koolhydraten" },
  { naam: "vastkokende aardappelen", categorie: "koolhydraten" },
  { naam: "krieltjes", categorie: "koolhydraten" },
  { naam: "frites", categorie: "koolhydraten" },
  { naam: "aardappelpuree", categorie: "koolhydraten" },
  { naam: "rijst", categorie: "koolhydraten" },
  { naam: "witte rijst", categorie: "koolhydraten" },
  { naam: "zilvervliesrijst", categorie: "koolhydraten" },
  { naam: "basmatirijst", categorie: "koolhydraten" },
  { naam: "jasmine rijst", categorie: "koolhydraten" },
  { naam: "pasta", categorie: "koolhydraten" },
  { naam: "spaghetti", categorie: "koolhydraten" },
  { naam: "penne", categorie: "koolhydraten" },
  { naam: "fusilli", categorie: "koolhydraten" },
  { naam: "tagliatelle", categorie: "koolhydraten" },
  { naam: "lasagnebladen", categorie: "koolhydraten" },
  { naam: "macaroni", categorie: "koolhydraten" },
  { naam: "couscous", categorie: "koolhydraten" },
  { naam: "quinoa", categorie: "koolhydraten" },
  { naam: "bulgur", categorie: "koolhydraten" },
  { naam: "polenta", categorie: "koolhydraten" },
  { naam: "noedels", categorie: "koolhydraten" },
  { naam: "rijstnoedels", categorie: "koolhydraten" },

  // Ontbijt & granen
  { naam: "havermout", categorie: "ontbijt" },
  { naam: "muesli", categorie: "ontbijt" },
  { naam: "granola", categorie: "ontbijt" },
  { naam: "cornflakes", categorie: "ontbijt" },
  { naam: "cruesli", categorie: "ontbijt" },
  { naam: "brinta", categorie: "ontbijt" },
  { naam: "sultana", categorie: "ontbijt" },
  { naam: "pindakaas", categorie: "ontbijt" },
  { naam: "notenpasta", categorie: "ontbijt" },
  { naam: "amandelboter", categorie: "ontbijt" },
  { naam: "jam", categorie: "ontbijt" },
  { naam: "aardbeijam", categorie: "ontbijt" },
  { naam: "appelstroop", categorie: "ontbijt" },
  { naam: "hagelslag", categorie: "ontbijt" },
  { naam: "chocoladepasta", categorie: "ontbijt" },
  { naam: "nutella", categorie: "ontbijt" },
  { naam: "honing", categorie: "ontbijt" },
  { naam: "siroop", categorie: "ontbijt" },
  { naam: "suiker", categorie: "ontbijt" },
  { naam: "basterdsuiker", categorie: "ontbijt" },
  { naam: "poedersuiker", categorie: "ontbijt" },

  // Sauzen & kruiden
  { naam: "tomatensaus", categorie: "sauzen" },
  { naam: "passata", categorie: "sauzen" },
  { naam: "ketchup", categorie: "sauzen" },
  { naam: "mayonaise", categorie: "sauzen" },
  { naam: "mosterd", categorie: "sauzen" },
  { naam: "sambal", categorie: "sauzen" },
  { naam: "sriracha", categorie: "sauzen" },
  { naam: "tabasco", categorie: "sauzen" },
  { naam: "sojasaus", categorie: "sauzen" },
  { naam: "ketjap", categorie: "sauzen" },
  { naam: "worcestersaus", categorie: "sauzen" },
  { naam: "pesto", categorie: "sauzen" },
  { naam: "rode pesto", categorie: "sauzen" },
  { naam: "groene pesto", categorie: "sauzen" },
  { naam: "hummus", categorie: "sauzen" },
  { naam: "tzatziki", categorie: "sauzen" },
  { naam: "barbecuesaus", categorie: "sauzen" },
  { naam: "currysaus", categorie: "sauzen" },
  { naam: "satésaus", categorie: "sauzen" },
  { naam: "olijfolie", categorie: "sauzen" },
  { naam: "zonnebloemolie", categorie: "sauzen" },
  { naam: "kokosolie", categorie: "sauzen" },
  { naam: "azijn", categorie: "sauzen" },
  { naam: "balsamicoazijn", categorie: "sauzen" },
  { naam: "zout", categorie: "sauzen" },
  { naam: "peper", categorie: "sauzen" },
  { naam: "paprikapoeder", categorie: "sauzen" },
  { naam: "komijnpoeder", categorie: "sauzen" },
  { naam: "kurkuma", categorie: "sauzen" },
  { naam: "kerrie", categorie: "sauzen" },
  { naam: "kaneel", categorie: "sauzen" },
  { naam: "nootmuskaat", categorie: "sauzen" },
  { naam: "oregano", categorie: "sauzen" },
  { naam: "thijm", categorie: "sauzen" },
  { naam: "rozemarijn", categorie: "sauzen" },
  { naam: "laurier", categorie: "sauzen" },
  { naam: "bouillonblokjes", categorie: "sauzen" },
  { naam: "soepbasis", categorie: "sauzen" },

  // Conserven & blik
  { naam: "tomaten in blik", categorie: "conserven" },
  { naam: "gepelde tomaten", categorie: "conserven" },
  { naam: "kikkererwten", categorie: "conserven" },
  { naam: "kidneybonen", categorie: "conserven" },
  { naam: "witte bonen", categorie: "conserven" },
  { naam: "bruine bonen", categorie: "conserven" },
  { naam: "linzen", categorie: "conserven" },
  { naam: "rode linzen", categorie: "conserven" },
  { naam: "groene linzen", categorie: "conserven" },
  { naam: "maïs in blik", categorie: "conserven" },
  { naam: "olijven", categorie: "conserven" },
  { naam: "kappertjes", categorie: "conserven" },
  { naam: "augurken", categorie: "conserven" },
  { naam: "sardientjes", categorie: "conserven" },
  { naam: "zalm in blik", categorie: "conserven" },
  { naam: "soep in blik", categorie: "conserven" },
  { naam: "tomatenpuree", categorie: "conserven" },

  // Diepvries
  { naam: "diepvries groenten", categorie: "diepvries" },
  { naam: "diepvries spinazie", categorie: "diepvries" },
  { naam: "diepvries doperwten", categorie: "diepvries" },
  { naam: "diepvries broccoli", categorie: "diepvries" },
  { naam: "diepvries friet", categorie: "diepvries" },
  { naam: "diepvries pizza", categorie: "diepvries" },
  { naam: "diepvries vis", categorie: "diepvries" },
  { naam: "diepvries garnalen", categorie: "diepvries" },
  { naam: "ijs", categorie: "diepvries" },
  { naam: "roomijs", categorie: "diepvries" },
  { naam: "ijsjes", categorie: "diepvries" },

  // Dranken
  { naam: "water", categorie: "dranken" },
  { naam: "spa blauw", categorie: "dranken" },
  { naam: "bruisend water", categorie: "dranken" },
  { naam: "sinaasappelsap", categorie: "dranken" },
  { naam: "appelsap", categorie: "dranken" },
  { naam: "vruchtensap", categorie: "dranken" },
  { naam: "smoothie", categorie: "dranken" },
  { naam: "cola", categorie: "dranken" },
  { naam: "frisdrank", categorie: "dranken" },
  { naam: "limonade", categorie: "dranken" },
  { naam: "ice tea", categorie: "dranken" },
  { naam: "thee", categorie: "dranken" },
  { naam: "groene thee", categorie: "dranken" },
  { naam: "koffie", categorie: "dranken" },
  { naam: "koffiecups", categorie: "dranken" },
  { naam: "instantkoffie", categorie: "dranken" },
  { naam: "filterkoffie", categorie: "dranken" },
  { naam: "espresso", categorie: "dranken" },
  { naam: "bier", categorie: "dranken" },
  { naam: "wijn", categorie: "dranken" },
  { naam: "rode wijn", categorie: "dranken" },
  { naam: "witte wijn", categorie: "dranken" },
  { naam: "cacao", categorie: "dranken" },
  { naam: "chocolademelk", categorie: "dranken" },

  // Snacks & koek
  { naam: "chips", categorie: "snacks" },
  { naam: "paprika chips", categorie: "snacks" },
  { naam: "naturel chips", categorie: "snacks" },
  { naam: "noten", categorie: "snacks" },
  { naam: "pinda's", categorie: "snacks" },
  { naam: "cashewnoten", categorie: "snacks" },
  { naam: "amandelen", categorie: "snacks" },
  { naam: "walnoten", categorie: "snacks" },
  { naam: "hazelnoten", categorie: "snacks" },
  { naam: "studentenhaver", categorie: "snacks" },
  { naam: "gedroogd fruit", categorie: "snacks" },
  { naam: "rozijnen", categorie: "snacks" },
  { naam: "dadels", categorie: "snacks" },
  { naam: "koekjes", categorie: "snacks" },
  { naam: "stroopwafels", categorie: "snacks" },
  { naam: "speculaas", categorie: "snacks" },
  { naam: "digestive biscuits", categorie: "snacks" },
  { naam: "wafels", categorie: "snacks" },
  { naam: "chocolade", categorie: "snacks" },
  { naam: "pure chocolade", categorie: "snacks" },
  { naam: "melkchocolade", categorie: "snacks" },
  { naam: "chocoladereep", categorie: "snacks" },
  { naam: "snoep", categorie: "snacks" },
  { naam: "drop", categorie: "snacks" },
  { naam: "kauwgom", categorie: "snacks" },
  { naam: "popcorn", categorie: "snacks" },
  { naam: "pretzels", categorie: "snacks" },
  { naam: "rijstwafels", categorie: "snacks" },
  { naam: "mueslirepen", categorie: "snacks" },

  // Bakken
  { naam: "bloem", categorie: "bakken" },
  { naam: "zelfrijzend bakmeel", categorie: "bakken" },
  { naam: "bakpoeder", categorie: "bakken" },
  { naam: "baking soda", categorie: "bakken" },
  { naam: "gist", categorie: "bakken" },
  { naam: "vanillesuiker", categorie: "bakken" },
  { naam: "vanille-extract", categorie: "bakken" },
  { naam: "cacao poeder", categorie: "bakken" },
  { naam: "maizena", categorie: "bakken" },
  { naam: "amandelpoeder", categorie: "bakken" },
  { naam: "kokosrasp", categorie: "bakken" },
  { naam: "rozijnen", categorie: "bakken" },
  { naam: "gedroogde cranberry's", categorie: "bakken" },
  { naam: "chocoladestukjes", categorie: "bakken" },

  // Persoonlijke verzorging & huishouden
  { naam: "wasmiddel", categorie: "huishouden" },
  { naam: "vaatwastabletten", categorie: "huishouden" },
  { naam: "afwasmiddel", categorie: "huishouden" },
  { naam: "allesreiniger", categorie: "huishouden" },
  { naam: "wc-papier", categorie: "huishouden" },
  { naam: "keukenpapier", categorie: "huishouden" },
  { naam: "vuilniszakken", categorie: "huishouden" },
  { naam: "aluminiumfolie", categorie: "huishouden" },
  { naam: "bakpapier", categorie: "huishouden" },
  { naam: "plasticfolie", categorie: "huishouden" },
  { naam: "tandpasta", categorie: "huishouden" },
  { naam: "shampoo", categorie: "huishouden" },
  { naam: "conditioner", categorie: "huishouden" },
  { naam: "douchegel", categorie: "huishouden" },
  { naam: "zeep", categorie: "huishouden" },
  { naam: "deodorant", categorie: "huishouden" },
  { naam: "scheerschuim", categorie: "huishouden" },
  { naam: "tissues", categorie: "huishouden" },
  { naam: "luiers", categorie: "huishouden" },

  // Plantaardig & biologisch
  { naam: "tofu", categorie: "plantaardig" },
  { naam: "tempeh", categorie: "plantaardig" },
  { naam: "seitan", categorie: "plantaardig" },
  { naam: "quorn", categorie: "plantaardig" },
  { naam: "vegetarische burger", categorie: "plantaardig" },
  { naam: "vegaballetjes", categorie: "plantaardig" },
  { naam: "sojagehakt", categorie: "plantaardig" },
  { naam: "vegarookworst", categorie: "plantaardig" },
  { naam: "biologische melk", categorie: "plantaardig" },
  { naam: "biologische yoghurt", categorie: "plantaardig" },
  { naam: "biologische eieren", categorie: "plantaardig" },
  { naam: "biologische appels", categorie: "plantaardig" },
  { naam: "biologische spinazie", categorie: "plantaardig" },
]

// Welke categorieën worden vaak gecombineerd
export const VERWANTE_CATEGORIEËN: Record<string, string[]> = {
  zuivel: ["brood", "ontbijt", "kaas"],
  brood: ["kaas", "vleeswaren", "zuivel", "ontbijt"],
  kaas: ["brood", "vleeswaren", "zuivel"],
  vleeswaren: ["brood", "kaas"],
  vlees: ["groenten", "koolhydraten", "sauzen"],
  vis: ["groenten", "koolhydraten", "sauzen"],
  groenten: ["vlees", "vis", "koolhydraten", "sauzen"],
  fruit: ["ontbijt", "zuivel", "snacks"],
  koolhydraten: ["vlees", "vis", "groenten", "sauzen"],
  ontbijt: ["zuivel", "fruit", "brood"],
  sauzen: ["vlees", "vis", "groenten", "koolhydraten"],
  conserven: ["koolhydraten", "sauzen", "groenten"],
  diepvries: ["sauzen", "koolhydraten"],
  dranken: ["snacks", "ontbijt"],
  snacks: ["dranken"],
  bakken: ["zuivel", "ontbijt"],
  huishouden: [],
  plantaardig: ["groenten", "koolhydraten", "sauzen"],
}

/** Zoek producten op naam (fuzzy prefix match) */
export function zoekProducten(invoer: string, max = 8): ProductSuggestie[] {
  if (!invoer.trim()) return []
  const q = invoer.toLowerCase().trim()
  return PRODUCTEN
    .filter((p) => p.naam.toLowerCase().includes(q))
    .sort((a, b) => {
      const aStart = a.naam.toLowerCase().startsWith(q) ? 0 : 1
      const bStart = b.naam.toLowerCase().startsWith(q) ? 0 : 1
      return aStart - bStart || a.naam.localeCompare(b.naam)
    })
    .slice(0, max)
}

/** Geef suggesties op basis van al toegevoegde producten */
export function suggestiesToevoegen(
  toegevoegdeNamen: string[],
  max = 6
): ProductSuggestie[] {
  if (toegevoegdeNamen.length === 0) return []

  const toegevoegdeCats = new Set(
    PRODUCTEN
      .filter((p) => toegevoegdeNamen.includes(p.naam))
      .map((p) => p.categorie)
  )

  const verwanteCats = new Set<string>()
  toegevoegdeCats.forEach((cat) => {
    VERWANTE_CATEGORIEËN[cat]?.forEach((v) => {
      if (!toegevoegdeCats.has(v)) verwanteCats.add(v)
    })
  })

  return PRODUCTEN
    .filter(
      (p) =>
        verwanteCats.has(p.categorie) &&
        !toegevoegdeNamen.includes(p.naam)
    )
    .slice(0, max)
}
